"use strict";
// Dashboard independiente: solo lee JSON existentes, no modifica scripts SAP.
const URLS={ordenes:"../data/ordenes_sap.json",avisos:"../data/avisos.json",programacion:"../data/programacion.json"};
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat("es-EC").format(n);
const money=n=>new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(n);
const number=v=>{if(v===null||v===undefined||v==="")return 0;const n=Number(v);return Number.isFinite(n)?n:0};
const str=v=>String(v??"").trim();
const key=v=>str(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
const field=(obj,names)=>{if(!obj||typeof obj!=="object")return "";const keys=Object.keys(obj);for(const name of names){const match=keys.find(k=>key(k)===key(name));if(match&&obj[match]!==null&&obj[match]!==undefined&&str(obj[match])!=="")return obj[match]}return ""};
const normalizeOrder=v=>str(v).replace(/\.0$/,"").replace(/^0+(?=\d)/,"");
const date=v=>{if(v===null||v===undefined||v==="")return null;if(typeof v==="number"&&v>20000&&v<80000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return Number.isNaN(d.getTime())?null:d}const s=str(v);let m=s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})/);if(m){const d=new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));return d.getUTCFullYear()===+m[3]&&d.getUTCMonth()===+m[2]-1&&d.getUTCDate()===+m[1]?d:null}m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m){const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));return d.getUTCFullYear()===+m[1]&&d.getUTCMonth()===+m[2]-1&&d.getUTCDate()===+m[3]?d:null}return null};
const displayDate=d=>d?`${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCMonth()+1).padStart(2,"0")}/${d.getUTCFullYear()}`:"—";
const months=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
const state=v=>{const s=str(v).toUpperCase();if(s.includes("CERRAD"))return "cerrada";if(s.includes("ABIERT"))return "abierta";return "revisar"};
let rows=[],sourceStatus="",signature="";
const avisosOrder=["orden","orden de trabajo","n orden","nro orden","numero orden","numero de orden","orden mantenimiento","orden asociada","orden sap","orden_1"];
const avisosDesc=["descripcion_1","descripcion 1","descripcion","texto breve","texto breve aviso","descripcion aviso","texto aviso"];
const avisosDate=["fecha aviso","fecha de aviso","fecha creacion","fecha de creacion","fecha","fecha aviso creado","fecha de entrada","fecha entrada"];
const progDate=["fecha","fecha programada","fecha de programacion"];
const classFields=["cl actividad pm","cl.actividad pm","clase actividad pm","clase de actividad pm","actividad pm","tipo mantenimiento","clasificacion mantenimiento"];
function build(orders,avisos,programacion){
 const avisosMap=new Map();for(const a of avisos){const order=normalizeOrder(field(a,avisosOrder));if(!order)continue;const d=date(field(a,avisosDate));const desc=str(field(a,avisosDesc));const cls=str(field(a,classFields));const old=avisosMap.get(order);if(!old||(!old.desc&&desc)||(!old.d&&d))avisosMap.set(order,{desc:desc||old?.desc||"",d:d||old?.d||null,cls:cls||old?.cls||""})}
 const progMap=new Map();for(const p of programacion){const order=normalizeOrder(field(p,["orden","orden #","numero orden"]));const d=date(field(p,progDate));if(!order||!d)continue;const old=progMap.get(order);if(!old||d<old)progMap.set(order,d)}
 return orders.map(o=>{const order=normalizeOrder(field(o,["orden"]));const aviso=avisosMap.get(order);const prog=progMap.get(order);const ref=date(field(o,["Fecha ref.","fecha_ref","fecha referencia","fecha_referencia"]));const d=ref||prog||aviso?.d||null;return {...o,_orden:order,_estado:state(field(o,["Status sistema PLANNER","estado_orden"])),_descripcion:str(field(o,["Texto breve","descripcion","Descripción"]))||aviso?.desc||"",_fecha:d,_fechaOrigen:ref?"IW39 · Fecha ref.":prog?"Programación (provisional)":aviso?.d?"Aviso (provisional)":"",_clase:str(field(o,classFields))||aviso?.cls||"",_tieneFechaRef:!!ref}})
}
function populate(id,values,all="Todos"){const select=$(id),prev=select.value;select.replaceChildren(new Option(all,""),...values.map(v=>new Option(v.label??v.value,v.value)));select.value=values.some(v=>v.value===prev)?prev:""}
function filters(){const years=[...new Set(rows.filter(x=>x._fecha).map(x=>x._fecha.getUTCFullYear()))].sort((a,b)=>b-a).map(v=>({value:String(v),label:String(v)}));populate("anio",years);populate("mes",months.map((m,i)=>({value:String(i+1),label:m})));populate("estado",[...new Set(rows.map(x=>str(field(x,["Status sistema PLANNER","estado_orden"]))).filter(Boolean))].sort().map(v=>({value:v,label:v}))) }
function empty(id,message){$(id).replaceChildren();const div=document.createElement("p");div.className="empty";div.textContent=message;$(id).append(div)}
function barChart(id,entries,total){const root=$(id);root.replaceChildren();if(!entries.length){empty(id,"No hay registros para los filtros seleccionados.");return}for(const [label,n] of entries){const r=document.createElement("div");r.className="bar";const l=document.createElement("label");l.textContent=label;l.title=label;const track=document.createElement("div");track.className="track";const fill=document.createElement("div");fill.className="fill";fill.style.width=`${total?100*n/total:0}%`;track.append(fill);const count=document.createElement("b");count.textContent=fmt(n);r.append(l,track,count);root.append(r)}}
function stackedChart(id,entries){const root=$(id);root.replaceChildren();if(!entries.length){empty(id,"No hay datos relacionados disponibles.");return}const legend=document.createElement("div");legend.className="legend";for(const [label,css] of [["Cerradas","closed"],["Abiertas","open"],["Revisar","review"]]){const el=document.createElement("span");const dot=document.createElement("i");dot.className="dot "+css;el.append(dot,document.createTextNode(label));legend.append(el)}root.append(legend);const max=Math.max(...entries.map(x=>x.cerrada+x.abierta+x.revisar),1);for(const x of entries){const total=x.cerrada+x.abierta+x.revisar;const r=document.createElement("div");r.className="bar";const l=document.createElement("label");l.textContent=x.label;l.title=x.label;const track=document.createElement("div");track.className="track";const stack=document.createElement("div");stack.className="stacked";stack.style.width=`${100*total/max}%`;for(const type of ["cerrada","abierta","revisar"]){if(x[type]){const part=document.createElement("div");part.className=type==="cerrada"?"closed":type==="abierta"?"open":"review";part.style.width=`${100*x[type]/total}%`;part.title=`${type}: ${fmt(x[type])}`;stack.append(part)}}track.append(stack);const count=document.createElement("b");count.textContent=fmt(total);r.append(l,track,count);root.append(r)}}
function aggregate(data,getLabel,limit=0){const map=new Map();for(const x of data){const label=getLabel(x);if(!label)continue;if(!map.has(label))map.set(label,{label,cerrada:0,abierta:0,revisar:0});map.get(label)[x._estado]++}let entries=[...map.values()];entries.sort((a,b)=>(b.cerrada+b.abierta+b.revisar)-(a.cerrada+a.abierta+a.revisar));return limit?entries.slice(0,limit):entries}
function render(){const st=$("estado").value,year=$("anio").value,month=$("mes").value,query=$("buscar").value.trim();const data=rows.filter(x=>(!st||str(field(x,["Status sistema PLANNER","estado_orden"]))===st)&&(!query||x._orden.includes(query))&&(!year||(x._fecha&&String(x._fecha.getUTCFullYear())===year))&&(!month||(x._fecha&&String(x._fecha.getUTCMonth()+1)===month)));const closed=data.filter(x=>x._estado==="cerrada").length,open=data.filter(x=>x._estado==="abierta").length;$("total").textContent=fmt(data.length);$("cerradas").textContent=fmt(closed);$("abiertas").textContent=fmt(open);$("cierre").textContent=data.length?(100*closed/data.length).toFixed(1)+"%":"—";$("plan").textContent=money(data.reduce((s,x)=>s+number(x.total_costes_plan),0));$("real").textContent=money(data.reduce((s,x)=>s+number(x.costes_totales_reales),0));const counts=new Map();data.forEach(x=>counts.set(str(field(x,["Status sistema PLANNER","estado_orden"]))||"Sin estado",(counts.get(str(field(x,["Status sistema PLANNER","estado_orden"]))||"Sin estado")||0)+1));barChart("barras",[...counts].sort((a,b)=>b[1]-a[1]),data.length);
 const byMonth=aggregate(data,x=>x._fecha?`${x._fecha.getUTCFullYear()}-${String(x._fecha.getUTCMonth()+1).padStart(2,"0")}`:"");byMonth.sort((a,b)=>a.label.localeCompare(b.label));byMonth.forEach(x=>{const [y,m]=x.label.split("-");x.label=months[Number(m)-1]+" "+y});stackedChart("mesesChart",byMonth);
 stackedChart("descripcionChart",aggregate(data,x=>x._descripcion,12));barChart("actividadChart",[...aggregate(data,x=>x._clase).map(x=>[x.label,x.cerrada+x.abierta+x.revisar])],data.length);
 const body=$("filas");body.replaceChildren();const frag=document.createDocumentFragment();for(const x of data.slice(0,250)){const tr=document.createElement("tr");for(const v of [x._orden,str(field(x,["Status sistema PLANNER","estado_orden"])),x._descripcion||"—",displayDate(x._fecha),x._fechaOrigen||"—",x._clase||"—",money(number(x.total_costes_plan)),money(number(x.costes_totales_reales)),x.fecha_iw47||"—",x.texto_notificacion||"—"]){const td=document.createElement("td");td.textContent=str(v);td.title=str(v);tr.append(td)}frag.append(tr)}body.append(frag);$("cantidad").textContent=`${fmt(data.length)} órdenes · ${fmt(data.filter(x=>x._tieneFechaRef).length)} con Fecha ref. IW39 · ${fmt(data.filter(x=>x._fecha&&!x._tieneFechaRef).length)} con fecha provisional`}
async function read(url){const res=await fetch(url+"?t="+Date.now(),{cache:"no-store"});if(!res.ok)throw Error("HTTP "+res.status);const json=await res.json();return {data:Array.isArray(json)?json:Array.isArray(json.data)?json.data:[],update:json.ultima_actualizacion||""}}
async function load(force=false){try{const results=await Promise.allSettled([read(URLS.ordenes),read(URLS.avisos),read(URLS.programacion)]);if(results[0].status!=="fulfilled")throw Error("No se pudo leer ordenes_sap.json: "+results[0].reason);const orders=results[0].value;const avisos=results[1].status==="fulfilled"?results[1].value.data:[];const programacion=results[2].status==="fulfilled"?results[2].value.data:[];const sig=JSON.stringify([orders.update,orders.data.length,results[1].status==="fulfilled"?results[1].value.update:"error",avisos.length,results[2].status==="fulfilled"?results[2].value.update:"error",programacion.length]);if(force||sig!==signature){signature=sig;rows=build(orders.data,avisos,programacion);filters();render()}const refCount=rows.filter(x=>x._tieneFechaRef).length;const errors=[];if(results[1].status!=="fulfilled")errors.push("avisos.json no disponible");if(results[2].status!=="fulfilled")errors.push("programacion.json no disponible");$("status").textContent=`Órdenes: ${fmt(rows.length)} · Fecha ref. IW39: ${fmt(refCount)} · Avisos cargados: ${fmt(avisos.length)} · Programación: ${fmt(programacion.length)} · Origen: ${orders.update||"sin fecha"} · Verificado: ${new Date().toLocaleTimeString("es-EC")}`+(refCount<rows.length?" · ADVERTENCIA: sin Fecha ref. IW39 para "+fmt(rows.length-refCount)+" órdenes; filtros de fecha provisionales":"")+(errors.length?" · ADVERTENCIA: "+errors.join(", "):"") }catch(e){$("status").textContent="Error de lectura: "+e.message;console.error(e)}}
for(const id of ["estado","anio","mes"])$(id).addEventListener("change",render);$("buscar").addEventListener("input",render);$("actualizar").addEventListener("click",()=>load(true));$("limpiar").addEventListener("click",()=>{for(const id of ["estado","anio","mes","buscar"])$(id).value="";render()});load(true);setInterval(()=>load(),60000);
